apiVersion: v1
kind: ConfigMap
metadata:
  name: morphdb-config
  namespace: morphdb
  labels:
    app.kubernetes.io/name: morphdb
    app.kubernetes.io/component: config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
