apiVersion: v1
kind: Service
metadata:
  name: morphdb-api
  namespace: morphdb
  labels:
    app.kubernetes.io/name: morphdb
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: morphdb
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: morphdb-api-headless
  namespace: morphdb
  labels:
    app.kubernetes.io/name: morphdb
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: morphdb
    app.kubernetes.io/component: api
