<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MorphDB.Npgsql</RootNamespace>
    <Description>PostgreSQL implementation for MorphDB</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MorphDB.Core\MorphDB.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MorphDB.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="SqlKata" />
    <PackageReference Include="SqlKata.Execution" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Polly" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

</Project>
